mods = {
    'planetary_diversity': {
        'planets' : [
            'pc_pd_wet_superhabitable',
            'pc_pd_dry_superhabitable',
            'pc_pd_cold_superhabitable',

            'pc_pd_wet_tidally_locked',
            'pc_pd_dry_tidally_locked',
            'pc_pd_cold_tidally_locked',

            'pc_pd_wet_cave',
            'pc_pd_dry_cave',
            'pc_pd_cold_cave',

            'pc_pd_forest',
            'pc_pd_retinal',
            'pc_pd_tepid',
            'pc_pd_lake',
            'pc_pd_mushroom',
            'pc_pd_megaflora',
            'pc_pd_petrified',

            'pc_pd_crag',
            'pc_pd_cascadian',
            'pc_pd_fog',
            'pc_pd_swamp',
            'pc_pd_kelp',
            'pc_pd_algae',
            'pc_pd_archipelago',
            'pc_pd_reef',

            'pc_pd_tepui',
            'pc_pd_atoll',
            'pc_pd_cenote',
            'pc_pd_mangrove',
            'pc_pd_fungal',
            'pc_pd_aerial',
            'pc_pd_lilypad',
            'pc_pd_geothermal',
            'pc_pd_biolumen',

            'pc_pd_outback',
            'pc_pd_dune',
            'pc_pd_coastal',
            'pc_pd_oasis',
            'pc_pd_fungi',
            'pc_pd_salt',
            'pc_pd_aquifer',

            'pc_pd_mediterranean',
            'pc_pd_mesa',
            'pc_pd_badlands',
            'pc_pd_fog_desert',
            'pc_pd_succulent',
            'pc_pd_striped',
            'pc_pd_coral',
            'pc_pd_primal',

            'pc_pd_veld',
            'pc_pd_steppe',
            'pc_pd_semi_arid',
            'pc_pd_prairie',
            'pc_pd_aspen',
            'pc_pd_sandstone',
            'pc_pd_supercontinent',
            'pc_pd_sinkhole',

            'pc_pd_antarctic',
            'pc_pd_cold_desert',
            'pc_pd_aeolian',
            'pc_pd_glacial',
            'pc_pd_ice_spike',
            'pc_pd_crevasse',
            'pc_pd_ice_dunes',
            'pc_pd_storm',
            'pc_pd_iceberg',

            'pc_pd_snow',
            'pc_pd_highland',
            'pc_pd_dune_forest',
            'pc_pd_boreal',
            'pc_pd_fjord',
            'pc_pd_blossom',
            'pc_pd_glaciovolcanic',
            'pc_pd_lanthanide',

            'pc_pd_mud',
            'pc_pd_bog',
            'pc_pd_basalt',
            'pc_pd_mycelium',
            'pc_pd_tuya',
            'pc_pd_cryoflora',
            'pc_pd_lichen',
        ],
    },
};