mods = {
    'planetary_diversity': {
        'planets' : [
            'pc_retinal',
            'pc_cascadian',
            'pc_desertislands',
            'pc_sandsea',
            'pc_mesa',
            'pc_steppe',
            'pc_frozen_desert',
            'pc_highland',
            'pc_swamp',

            'pc_lake',
            'pc_wetswamp',
            'pc_mangrove',
            'pc_outback',
            'pc_hadesert',
            'pc_prairie',
            'pc_glacial',
            'pc_boreal',
            'pc_mushroom',

            'pc_forest',
            'pc_subarctic',
            'pc_hajungle',
            'pc_oasis',
            'pc_med',
            'pc_veld',
            'pc_antarctic',
            'pc_snow',
            'pc_mud',

            'pc_tepid',
            'pc_fog',
            'pc_cenote',
            'pc_coastal',
            'pc_badlands',
            'pc_semiarid',
            'pc_aeolian',
            'pc_duneforest',
            'pc_basalt',

            'pc_megaflora',
            'pc_pd_archipelago',
            'pc_geothermal',
            'pc_salt',
            'pc_coral',
            'pc_supercon',
            'pc_storm',
            'pc_glacio',
            'pc_cryoflora',

            'pc_pd_petrified',
            'pc_reef',
            'pc_biolumen',
            'pc_aquifer',
            'pc_primal',
            'pc_pd_sinkhole',
            'pc_pd_iceberg',
            'pc_lanthanide',
            'pc_lichen',

            'pc_superhabitable',
            'pc_wettidallylocked',
            'pc_karst',
            'pc_pd_dry_superhab',
            'pc_tidallylocked',
            'pc_pd_dry_cave',
            'pc_pd_cold_superhab',
            'pc_eyeball',
            'pc_pd_cold_cave',
        ],
    },
};