basegame_species = {
    'HUM'    : {
        secondary: true,
        portraits: [
            'human',
            'human_legacy',
            'humanoid_02',
            'humanoid_03',
            'humanoid_04',
            'humanoid_05',
            'humanoid_hp_01',
            'humanoid_hp_02',
            'humanoid_hp_06',
            'humanoid_hp_07',
            'humanoid_hp_08',
            'humanoid_hp_09',
            'humanoid_hp_10',
            'humanoid_hp_11',
            'humanoid_hp_12',
            'humanoid_hp_13',
            'humanoid_hp_14',
            'humanoid_elf',
            'humanoid_hp_16',
            'cyb8',
            'cyb12',
            'synth04',
            'synth07',
        ],
    },
    'MAM'    : {
        secondary: true,
        portraits: [
            'mam5',
            'mam13',
            'mam10',
            'mam14',
            'mam4',
            'mam9',
            'mam11',
            'mam6',
            'mam3',
            'mam12',
            'mam7',
            'mam15',
            'mam2',
            'mam8',
            'mam1',
            'mam16',
            'mam_rat',
            'mam17',
            'cyb1',
            'cyb2',
            'cyb3',
            'cyb6',
            'cyb7',
        ],
    },
    'REP'    : {
        secondary: true,
        portraits: [
            'rep2',
            'rep10',
            'rep14',
            'rep3',
            'rep7',
            'rep12',
            'rep9',
            'rep11',
            'rep6',
            'rep13',
            'rep1',
            'rep8',
            'rep4',
            'rep15',
            'rep5',
            'rep16',
            'rep17',
            'cyb4',
            'cyb10',
            'cyb11',
        ],
    },
    'AVI'    : {
        secondary: true,
        portraits: [
            'avi1',
            'avi8',
            'avi13',
            'avi10',
            'avi15',
            'avi4',
            'avi7',
            'avi5',
            'avi9',
            'avi6',
            'avi11',
            'avi3',
            'avi14',
            'avi2',
            'avi12',
            //'avi16',  // logged_in_to_pdx_account required?
            'avi17',
            'avi18',
            'cyb5',
            'synth01'
        ],
    },
    'ART'    : {
        secondary: true,
        portraits: [
            'art14',
            'art7',
            'art12',
            'art6',
            'art1',
            'art13',
            'art8',
            'art3',
            'art5',
            'art9',
            'art10',
            'art11',
            'art15',
            'art19',
            'art18',
            'art16',
            'art20',
            'art17',
            'cyb9',
            'synth02',
            'synth08',
            'synth09',
        ],
    },
    'MOL'    : {
        secondary: true,
        portraits: [
            'mol3',
            'mol7',
            'mol13',
            'mol2',
            'mol14',
            'mol4',
            'mol8',
            'mol1',
            'mol11',
            'mol12',
            'mol5',
            'mol6',
            'mol15',
            'mol16',
            'mol17',
            'mol18',
            'synth03',
            'synth05',
        ],
    },
    'FUN'    : {
        secondary: true,
        portraits: [
            'fun2',
            'fun4',
            'fun3',
            'fun13',
            'fun12',
            'fun6',
            'fun15',
            'fun7',
            'fun1',
            'fun9',
            'fun11',
            'fun8',
            'fun14',
            'fun10',
            'fun16',
            'fun17',
            'cyb13',
        ],
    },
    'PLANT'  : {
        secondary: true,
        portraits: [
            'pla2',
            'pla6',
            'pla1',
            'pla11',
            'pla3',
            'pla13',
            'pla7',
            'pla15',
            'pla10',
            'pla5',
            'pla9',
            'pla14',
            'pla4',
            'pla8',
            'pla12',
            'pla16_baol',
            'pla17',
        ],
    },
    'LITHOID': {
        secondary: true,
        portraits: [
            'lith1',
            'lith2',
            'lith3',
            'lith4',
            'lith5',
            'lith6',
            'lith7',
            'lith8',
            'lith9',
            'lith10',
            'lith11',
            'lith12',
            'lith13',
            'lith14',
            'lith15',
            'lith_human',
        ],
    },
    'AQUATIC': {
        secondary: true,
        portraits: [
            'aqu1',
            'aqu2',
            'aqu3',
            'aqu4',
            'aqu5',
            'aqu6',
            'aqu7',
            'aqu8',
            'aqu9',
            'aqu10',
            'aqu11',
            'aqu12',
            'aqu13',
            'aqu14',
            'aqu15',
            'synth06',
        ],
    },
    'TOX'    : {
        secondary: true,
        portraits: [
            'tox1',
            'tox2',
            'tox3',
            'tox4',
            'tox5',
            'tox6',
            'tox7',
            'tox8',
            'tox9',
            'tox10',
            'tox11',
            'tox12',
            'tox13',
            'tox14',
            'tox15',
        ],
    },
    'NECROID': {
        secondary: true,
        portraits: [
            'nec1',
            'nec2',
            'nec3',
            'nec4',
            'nec5',
            'nec6',
            'nec7',
            'nec8',
            'nec9',
            'nec10',
            'nec11',
            'nec12',
            'nec13',
            'nec14',
            'nec15',
        ],
    },
};

basegame_species_machine = {
    'MACHINE': {
        secondary: false,
        portraits: [
            'sd_hum_robot',
            'sd_mam_robot',
            'sd_rep_robot',
            'sd_avi_robot',
            'sd_art_robot',
            'sd_mol_robot',
            'sd_fun_robot',
            'sd_pla_robot',
            'lith_machine',
            'nec_machine',
            'aqu_machine',
            'tox_machine',
            'default_robot',
            'synth_machine_01',
            'synth_machine_02',
            'synth_machine_03',
            'synth_machine_04',
            'synth_machine_05',
            'synth_machine_06',
            'synth_machine_07',
            'synth_machine_08',
            'synth_machine_09',
            'cyb_machine',
        ],
    },
};